config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'statics#home'
  resources :users do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true

  def toggle_private(is_private) 
    self.is_private = is_private
  end

  def private?
    self.is_private
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true
  has_many :posts

  def create_post(post)
    posts << post
  end

  def public_posts
    posts.where('is_private = ?', false)
  end

  def private_posts
    posts.where('is_private = ?', true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected 
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
      devise_parameter_sanitizer.permit(:account_update, keys:[:username])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :authenticate_user!
  #before_action :owner_log_in, only: [:create]

  def create
    @user ||= User.find(params[:user_id])
    @post = Post.new(post_params)
    params[:post][:is_private] == '1' ? @post.toggle_private(true) : @post.toggle_private(false)

    if @user.create_post(@post)
      redirect_to user_path(@user), notice: 'Post created'
    else
      redirect_to user_path(@user), alert: 'Invalid post'
    end
  end

  private
    def owner_log_in
      @user = User.find(params[:user_id])
      unless current_user == @user
        redirect_to new_user_session_path, alert: "Please log in to your account"
      end
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = current_user == @user ? @user.posts : @user.public_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date) 
    date.strftime("%d/%m/%y")
  end

  def format_date_time(datetime)
    datetime.strftime("%k:%M %d/%m/%y")
  end

  def random_color
    @colors ||= %w[danger info success warning primary link]
    @colors[rand(@colors.count)]
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar(user, options = {})
    email_hash = Digest::MD5.hexdigest(user.email)
    size = options[:size] || 120
    url = "https://gravatar.com/avatar/#{email_hash}?s=#{size}"

    image_tag url, alt: 'Avatar Image', class: options[:class]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microposts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <div class="notification is-success">
        <%= notice %>
        <button class="delete"></button>
      </div>
    <% end %>

    <% if alert %>
      <div class="notification is-warning">
        <%= alert %>
        <button class="delete"></button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', () => {
  (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
    $notification = $delete.parentNode;
    $delete.addEventListener('click', () => {
      $notification.parentNode.removeChild($notification);
    });
  });
});
</script>

app/views/statics/home.html.erb
<section class="hero is-large is-primary">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item">
            <h1>Micropost</h1>
          </a>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <%= link_to 'All posts','#', class: 'navbar-item'%>
            <% if user_signed_in? %>
              <%= link_to 'Create post', '#', class: 'navbar-item'%>
              <%= link_to 'Log out', destroy_user_session_path, class: 'navbar-item', method: :delete%>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Welcome To Microposts
      </h1>
      <h2 class="subtitle">
        A minimum social media platform
      </h2>
      <div class="are-medium">
        <% unless user_signed_in? %>
          <%= link_to 'Login', new_user_session_path, class: 'button is-info is-large is-rounded' %>
        <% end %>
        
        <% if user_signed_in? %>
          <%= link_to 'View', user_path(current_user), class: 'button is-warning is-rounded is-large' %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<div class="columns">
  <div class="column is-half">
    <div class="hero is-danger is-fullheight" style="height: 100%">
      <!-- Hero head: will stick at the top -->
      <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div id="navbarMenuHeroB" class="navbar-menu">
              <div class="navbar-start">
                <%= link_to 'Home', root_path, class: 'navbar-item' %>
              </div>
            </div>
          </div>
        </nav>
      </div>
      
      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title is-1">Hi, I'm <%= @user.username %></h1>
          <p class="title is-5"><%= @user.email %></p>
          <%= avatar @user, class: 'is-rounded', size: 256 %>
          <p class="heading">Posts</p>
          <p class="title is-2"><%= @user.posts.count %></p>
        </div>
      </div>
    </div>
  </div>
  
  <div class="column is-half has-background-light messages">
    <!-- Comment box if logged in-->
    <% if current_user == @user %>
      <%= form_for(:post, url: user_posts_path(@user)) do |f| %>
        <div class="field">
          <div class="control">
            <%= f.text_field :title, class: 'input', placeholder: 'Title' %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.text_area :content, class: 'input', placeholder: 'Content' %>
          </div>
        </div>

        <%= f.check_box :is_private %>
        <%= f.label :is_private, "Private" %><br />

        <%= f.submit 'Create', class: 'button is-danger'%>
      <% end %>
    <% end %>

    <!-- Message Display -->
    <% @posts.each do |post| %>
      <div class="message is-<%= random_color %>">
        <div class="message-header">
          <%= post.title %>
          <% if current_user == @user %>
            <% if post.private? %>
              <span class="has-text-danger">/Private</span>
            <% else %>
              <span class="has-text-success">/Public</span>
            <% end %>
          <% end %>
        </div>
        <div class="message-body">
          <em>On <%= format_date_time(post.created_at) %></em>
          <p>
            <%= post.content %>
          </p>
      </div>
    <% end %>
  </div>
</div>